apiVersion: v1
kind: Service
metadata:
  name: backend-service  
  namespace: mern-app
  annotations:
      # Service-level health check path (higher priority)
      alb.ingress.kubernetes.io/healthcheck-path: /api/tasks
      alb.ingress.kubernetes.io/healthcheck-port: '3500'
      alb.ingress.kubernetes.io/success-codes: "200"
spec:
  type: ClusterIP # Default service type . used for internal communication . ingress can route to it 
  selector:
    app: backend # Selecting pods with label app: backend
  ports:
  - protocol: TCP
    port: 3500 # Exposing port 5000 on the service
    targetPort: 3500 # Target port on the backend pods
    