apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
  namespace: mern-app
type: Opaque
data:
  MONGO_USERNAME: dXNlcg==      # Base64 encoded value of "user"
  MONGO_PASSWORD: cGFzc3dvcmQ= # Base64 encoded value of "password"
