apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-configmap # ConfigMap for frontend application
  namespace: mern-app
data:
    REACT_APP_BACKEND_URL:  "/api/tasks" #"http://backend-service:3500/api/tasks" #"http://final-project.capstone/api/tasks" # URL for backend API
    REACT_APP_ENV: "production" # Environment variable indicating production environment