apiVersion: v1
kind: Service
metadata:
  name: frontend-service  
  namespace: mern-app
  annotations:
    # Distinct health check for frontend
    alb.ingress.kubernetes.io/healthcheck-path: /
    alb.ingress.kubernetes.io/healthcheck-port: '3000'
spec:
  type: ClusterIP # Default service type . used for internal communication . ingress can route to it 
  selector:
    app: frontend # Selecting pods with label app: frontend
  ports:
  - protocol: TCP
    #port: 80 # Exposing port 80 on the service
    #targetPort: 3000 # Mapping to container port 3000
    port: 3000 # Exposing port 3000 on the service